/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hastane;

import javax.swing.JOptionPane;

/**
 *
 * @author Muhammet
 */
public class DoktorKisiselBilgiler extends javax.swing.JFrame {

    /**
     * Creates new form DoktorKisiselBilgiler
     */
    int id;
    Doktor doktor=new Doktor();
    public DoktorKisiselBilgiler(int id) {
        this.id=id;
        initComponents();
    }
    public DoktorKisiselBilgiler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        Geri = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DoktorAd = new javax.swing.JTextField();
        DoktorSoyad = new javax.swing.JTextField();
        Klinik = new javax.swing.JTextField();
        Kaydet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Geri.setText("Geri");
        Geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeriActionPerformed(evt);
            }
        });
        jPanel1.add(Geri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 49, -1, -1));

        jLabel1.setText("Ad:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 109, 53, -1));

        jLabel2.setText("Soyad:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 151, 53, -1));

        jLabel3.setText("Klinik Adı:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 195, -1, -1));

        DoktorAd.setText(doktor.getAd(id));
        jPanel1.add(DoktorAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 106, 92, -1));

        DoktorSoyad.setText(doktor.getSoyad(id));
        jPanel1.add(DoktorSoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 148, 92, -1));

        Klinik.setText(doktor.getKlinik(id));
        jPanel1.add(Klinik, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 192, 92, -1));

        Kaydet.setText("Kaydet");
        Kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaydetActionPerformed(evt);
            }
        });
        jPanel1.add(Kaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 232, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(103, 294, 195, 268);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaydetActionPerformed
        // TODO add your handling code here:
        doktor.setAd(id, DoktorAd.getText());
        doktor.setSoyad(id, DoktorSoyad.getText());
        doktor.setKlinik(id, Klinik.getText());
        JOptionPane.showMessageDialog(null, " Bilgiler Güncellendi");


    }//GEN-LAST:event_KaydetActionPerformed

    private void GeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeriActionPerformed
        // TODO add your handling code here:
        DoktorMain newDoktorMain= new DoktorMain(id);
        newDoktorMain.setLocationRelativeTo(null);
        newDoktorMain.setVisible(true);
        dispose();
    }//GEN-LAST:event_GeriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoktorKisiselBilgiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoktorKisiselBilgiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoktorKisiselBilgiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoktorKisiselBilgiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoktorKisiselBilgiler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DoktorAd;
    private javax.swing.JTextField DoktorSoyad;
    private javax.swing.JButton Geri;
    private javax.swing.JButton Kaydet;
    private javax.swing.JTextField Klinik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
