/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hastane;

import javax.swing.JOptionPane;

/**
 *
 * @author Muhammet
 */
public class HastaBilgileri extends javax.swing.JFrame {

    public int id;
    Hasta hasta= new Hasta();
    
    public HastaBilgileri(int id) {
        this.id=id;
        initComponents();
    }
    public HastaBilgileri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        adText = new javax.swing.JTextField();
        soyadText = new javax.swing.JTextField();
        boyText = new javax.swing.JTextField();
        kiloText = new javax.swing.JTextField();
        yasText = new javax.swing.JTextField();
        Kaydet = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        GeriButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Boy");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 216, 46, -1));

        jLabel5.setText("Kilo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 256, 46, -1));

        jLabel6.setText("Yaş");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 303, 46, -1));

        adText.setText(hasta.getAd(id));
        jPanel1.add(adText, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 133, 100, -1));

        soyadText.setText(hasta.getSoyad(id));
        jPanel1.add(soyadText, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 173, 100, -1));

        boyText.setText(hasta.getBoy(id));
        jPanel1.add(boyText, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 213, 100, -1));

        kiloText.setText(hasta.getKilo(id));
        jPanel1.add(kiloText, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 256, 100, -1));

        yasText.setText(hasta.getYas(id));
        jPanel1.add(yasText, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 300, 100, -1));

        Kaydet.setText("Kaydet");
        Kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaydetActionPerformed(evt);
            }
        });
        jPanel1.add(Kaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 354, -1, -1));

        jLabel1.setText("Ad");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 133, 46, -1));

        GeriButton.setText("Geri");
        GeriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeriButtonActionPerformed(evt);
            }
        });
        jPanel1.add(GeriButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 27, -1, -1));

        jLabel2.setText("Soyad");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 176, 46, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 197, 135, 289);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaydetActionPerformed
        // TODO add your handling code here:
        String ad= adText.getText();
        String soyad = soyadText.getText();
        String boyString=boyText.getText();
        String kiloString=kiloText.getText();
        int boyValue,kiloValue;
        if(boyString.contains(" cm")){
            boyValue=Integer.valueOf(boyString.substring(0,boyString.length()-3));
        }
        else{
            boyValue=Integer.valueOf(boyString);
        }
        
         if(kiloString.contains("kg")){
           kiloValue=Integer.valueOf(kiloText.getText().substring(0,kiloText.getText().length()-3));
        }
        else{
            kiloValue=Integer.valueOf(kiloString);
        }
        
        
        int yasValue=Integer.valueOf(yasText.getText());
        
        
        hasta.setAd(id, ad);
        hasta.setSoyad(id, soyad);
        hasta.setKilo(id, kiloValue);
        hasta.setBoy(id, boyValue);
        hasta.setYas(id, yasValue);
        
        JOptionPane.showMessageDialog(null, "Bilgilerin değişimi başarılı");

    }//GEN-LAST:event_KaydetActionPerformed

    private void GeriButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeriButtonActionPerformed
        // TODO add your handling code here:
        HastaMainPage newHastaMainPage= new HastaMainPage(id);
        newHastaMainPage.setLocationRelativeTo(null);
        newHastaMainPage.setVisible(true);
        dispose();
    }//GEN-LAST:event_GeriButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HastaBilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HastaBilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HastaBilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HastaBilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HastaBilgileri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GeriButton;
    private javax.swing.JButton Kaydet;
    private javax.swing.JTextField adText;
    private javax.swing.JTextField boyText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kiloText;
    private javax.swing.JTextField soyadText;
    private javax.swing.JTextField yasText;
    // End of variables declaration//GEN-END:variables
}
