/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hastane;

import javax.swing.JOptionPane;

/**
 *
 * @author Muhammet
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Arkaplan = new javax.swing.JPanel();
        TcKimlik = new javax.swing.JTextField();
        Sifre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Giris = new javax.swing.JButton();
        Unvan = new javax.swing.JComboBox<>();
        kaydol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Arkaplan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TcKimlik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TcKimlikActionPerformed(evt);
            }
        });
        Arkaplan.add(TcKimlik, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 141, 30));
        Arkaplan.add(Sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 141, 30));

        jLabel1.setText("TC Kimlik No");
        Arkaplan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 80, 20));

        jLabel2.setText("Şifre");
        Arkaplan.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, 20));

        Giris.setText("Giriş Yap");
        Giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GirisActionPerformed(evt);
            }
        });
        Arkaplan.add(Giris, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 100, 30));

        Unvan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hasta", "doktor" }));
        Unvan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnvanActionPerformed(evt);
            }
        });
        Arkaplan.add(Unvan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, 30));

        kaydol.setText("Kaydol");
        kaydol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydolActionPerformed(evt);
            }
        });
        Arkaplan.add(kaydol, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 100, 30));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(121, 203, 221, 257);
        getContentPane().add(Arkaplan, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GirisActionPerformed
      
      String id = TcKimlik.getText();
      int idNumber= Integer.parseInt(id);
      String sifre= Sifre.getText();
      String unvan= (String) Unvan.getSelectedItem();
      Kullanicilar kullanici = new Kullanicilar(unvan,sifre,idNumber);
      if(kullanici.Baglan()){
          System.out.println("bağlandı"); 
          switch (unvan) {
              case "hasta":
                HastaMainPage HastaMain= new HastaMainPage(idNumber, "hasta");
                HastaMain.setLocationRelativeTo(null);  
                HastaMain.setVisible(true);
                break;
              case "doktor":
                DoktorMain doktorMain = new DoktorMain(idNumber);
                doktorMain.setLocationRelativeTo(null);  
                doktorMain.setVisible(true);
                break;
              default:
                  throw new AssertionError();
          }
          dispose();
      }
          
      else{
          JOptionPane.showMessageDialog(null, "Kullanıcı adı veya şifre yanlış");
          TcKimlik.setText("");
          Sifre.setText("");
      }  
    }//GEN-LAST:event_GirisActionPerformed

    private void UnvanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnvanActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_UnvanActionPerformed

    private void kaydolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydolActionPerformed
        // TODO add your handling code here:
        Kaydol kaydol= new Kaydol();
        kaydol.setLocationRelativeTo(null); 
        kaydol.setVisible(true);
        dispose();
    }//GEN-LAST:event_kaydolActionPerformed

    private void TcKimlikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TcKimlikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TcKimlikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Arkaplan;
    private javax.swing.JButton Giris;
    private javax.swing.JTextField Sifre;
    private javax.swing.JTextField TcKimlik;
    private javax.swing.JComboBox<String> Unvan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton kaydol;
    // End of variables declaration//GEN-END:variables
}
