/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hastane;
import static hastane.Baglanti.con;
import static hastane.Baglanti.statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Muhammet
 */
public class Randevu extends javax.swing.JFrame {

    public int id;
    public Date date;
    Hasta hasta= new Hasta();
    public Randevu(int id) {
        this.id=id;
        initComponents();
        
    }
    public Randevu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        GeriButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        RandevuTablo = new javax.swing.JTable();
        randevuSil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        RandevuEkle = new javax.swing.JTable();
        RandevuAl = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GeriButton.setText("Geri");
        GeriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeriButtonActionPerformed(evt);
            }
        });
        jPanel1.add(GeriButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 14, -1, -1));

        RandevuTablo.setModel(hasta.randevuGoster(id));
        jScrollPane2.setViewportView(RandevuTablo);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 76, 469, 203));

        randevuSil.setText("Randevu Sil");
        randevuSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randevuSilActionPerformed(evt);
            }
        });
        jPanel1.add(randevuSil, new org.netbeans.lib.awtextra.AbsoluteConstraints(919, 285, -1, -1));

        RandevuEkle.setModel(hasta.alinmamisRandevuGoster(id));
        jScrollPane1.setViewportView(RandevuEkle);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 76, -1, 203));

        RandevuAl.setText("Randevu Al");
        RandevuAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandevuAlActionPerformed(evt);
            }
        });
        jPanel1.add(RandevuAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 285, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 44, 84, 6);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void randevuSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randevuSilActionPerformed
        // TODO add your handling code here:
        hasta.randevuIptal(id, RandevuTablo, RandevuEkle);
        
    }//GEN-LAST:event_randevuSilActionPerformed

    private void RandevuAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandevuAlActionPerformed
        // TODO add your handling code here:
        hasta.randevuAl(id, RandevuEkle,RandevuTablo);
    }//GEN-LAST:event_RandevuAlActionPerformed

    private void GeriButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeriButtonActionPerformed
        // TODO add your handling code here:
        HastaMainPage newMainPage = new HastaMainPage(id);
        newMainPage.setLocationRelativeTo(null);
        newMainPage.setVisible(true);
        dispose();
    }//GEN-LAST:event_GeriButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Randevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Randevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Randevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Randevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Randevu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GeriButton;
    private javax.swing.JButton RandevuAl;
    private javax.swing.JTable RandevuEkle;
    private javax.swing.JTable RandevuTablo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton randevuSil;
    // End of variables declaration//GEN-END:variables
}
